exclude: '(^docs|.rst$|.html$)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: forbid-new-submodules
    -   id: end-of-file-fixer

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8

# Current not used - notebook output is kept for demonstration
# - repo: https://github.com/kynan/nbstripout
#   rev: 0.5.0
#   hooks:
#     - id: nbstripout
